export const STORAGE_KEYS = {
    TOKEN: 'TOKEN',
    LANGUAGE: 'LANGUAGE',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    USER_DATA: 'USER_DATA',
    USER_ID: 'USER_ID',
    ROLES: 'ROLES',
    USER_RANDOM: 'USER_RANDOM'
}